// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-neighborhoods.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
import { neighborhoods } from "npm:@/data/neighborhoods";
var get_neighborhoods_default = defineTool({
  name: "get_neighborhoods",
  title: "Get Turin neighborhoods",
  description: "List Turin neighborhoods for students with average rent, safety, transport and student profile. Optional slug filter returns a single neighborhood.",
  inputSchema: {
    slug: z.string().optional().describe("Optional neighborhood slug (e.g. 'san-salvario'). If omitted, returns all."),
    lang: z.enum(["it", "en"]).optional().describe("Language for text fields. Default 'it'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug, lang }) => {
    const language = lang ?? "it";
    const list = slug ? neighborhoods.filter((n) => n.slug === slug) : neighborhoods;
    const data = list.map((n) => ({
      slug: n.slug,
      name: n.name,
      zone: n.zone,
      description: n.description[language],
      avgRent: n.avgRent,
      universities: n.universities,
      transport: n.transport,
      safety: n.safety,
      nightlife: n.nightlife,
      studentDensity: n.studentDensity,
      url: `https://junglerent.it/${language === "it" ? "affitto-stanza-torino" : "rooms-rent-turin"}/${n.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { neighborhoods: data }
    };
  }
});

// src/lib/mcp/tools/get-investor-zones.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
import { investorZones, getZoneBySlug } from "npm:@/data/investorZoneData";
var get_investor_zones_default = defineTool2({
  name: "get_investor_zones",
  title: "Get Turin investor zones",
  description: "List Turin real-estate investor zones with entry prices, urban renewal projects and market metrics. Return figures projections are NOT included (confidential, memorandum only). Optional slug filter returns one zone.",
  inputSchema: {
    slug: z2.string().optional().describe("Optional zone slug. If omitted, returns all zones.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const zones = slug ? [getZoneBySlug(slug)].filter(Boolean) : investorZones;
    return {
      content: [{ type: "text", text: JSON.stringify(zones, null, 2) }],
      structuredContent: { zones }
    };
  }
});

// src/lib/mcp/tools/contact-jungle-rent.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
var contact_jungle_rent_default = defineTool3({
  name: "contact_jungle_rent",
  title: "Contact Jungle Rent",
  description: "Return the primary contact channels for Jungle Rent (WhatsApp with founder Lorenzo, email, website). Use when a user asks how to get in touch, book a call, or send an inquiry.",
  inputSchema: {
    topic: z3.enum(["investor", "student", "seller", "tourist", "general"]).optional().describe("Inquiry topic. Defaults to 'general'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topic }) => {
    const info = {
      topic: topic ?? "general",
      whatsapp: "https://wa.me/393773820849",
      email: "ciao@junglerent.it",
      website: "https://junglerent.it",
      primary_cta: "Parla con Lorenzo su WhatsApp",
      note: "WhatsApp is the fastest channel. Lorenzo Oni-Joseph is the sole founder."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jungle-rent-mcp",
  title: "Jungle Rent MCP",
  version: "0.1.0",
  instructions: "Tools for Jungle Rent \u2014 Turin student housing and real-estate investment. Use `get_neighborhoods` for student rental zones, `get_investor_zones` for investor market data (no yield projections \u2014 those are confidential), and `contact_jungle_rent` to share contact channels.",
  tools: [get_neighborhoods_default, get_investor_zones_default, contact_jungle_rent_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
